### ISSUE TITLE
Function returns address of data on the stack

### ISSUE THREAD

**Issue by rhempel** [sahil-kale/voyager-bootloader-demo#1]
https://github.com/sahil-kale/voyager-bootloader-demo/blob/3847aa3623c44b31123a54e9da9d22e7ea7238dd/target/Core/Src/voyager_host.c#L147C7-L147C7

I believe this is a potential subtle bug - you are returning the address of a structure on the stack, which is absolutely not guaranteed to be valid after this function exits.

**Comment by sahil-kale** [comment]
Interesting - I ended up rabbit-holing on the topic because I misunderstood your question 😅. The function itself doesn't return address but the local copy  `application_info_flash_t ` , hard agreed that it's UB to return an address of a local.

That being said, the misinterpretation because I wasn't returning an address-of-local sent me down a rabbit hole about how the return keyword works and how the object is copied over when the stack frame is no longer in scope :) https://cplusplus.com/forum/beginner/271830/
